package logic

const (
	CLOSECLT_NOTIFY = 0
	ACCOUNTINFO_REQ = 1
	ACCOUNTINFO_RSP = 2
	ACCOUNTREG_REQ  = 3
	ACCOUNTREG_RSP  = 4
)

const (
	ERR_NONE             = 0
	ERR_ACTNOTEXIST      = 1
	ERR_REGACCOUNTFAILED = 2
	ERR_ACCOUNTHASEXIST  = 3
)
